### ISSUE TITLE
Usability for action when graph is empty

### ISSUE THREAD

**Issue by husaynali** [Semantic-Society/Neologism#103]
Idea is to indicate the immediate action when a user enters the graph editor for a newly created vocab or when the graph is empty.
For this, it is proposed to show a button for creating a class node with such focus that is 

- it shall be centred
- and button with overlay on the view
- or button centred on the canvas

**Comment by JohannesLipp** [comment]
Possible idea: Add an overlay above mxGraph component and display a button there.
