### ISSUE TITLE
Prepare docker setup for local execution

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#117]
Our [current Dockerfile hat a URL hardcoded](https://github.com/Semantic-Society/Neologism/blob/main/frontend/Dockerfile#L8), which makes local execution complex. Please investigate this once more to make it more flexible. Thanks!

**Comment by JohannesLipp** [comment]
@husaynali Please give a short manual how to run Neologism locally, thanks! That probably involves manipulating that APP_ROOT_URL and build with Docker, right?

**Comment by husaynali** [comment]
The URL is default/optional but not hardcoded in the abstract sense and is overridden by the compose.yml build args. I shall remove that in the future to eliminate the confusion. For a quick win to run locally I would suggest running the following commands in the subfolder frontend:

1. `docker-compose build`
2. `docker-compose -f docker-compose.yml -f docker-compose.Hussain.yml`

After this, you shall get the page on localhost.
But you still cannot log in as the registration is turned off. But if we create a manual entry for the user.

NOTE:
port 80 and 3000 should be free on the host. In the case of Nginx, you need to stop.
