### ISSUE TITLE
Finalize between two styling themes material/ng-zorro-ant

### ISSUE THREAD

**Issue by husaynali** [Semantic-Society/Neologism#120]
Angular project views are using components from two DIFFERENT themes

- ng.ant.design 7.5.x
- angular material

which makes styling overall inconsistent. Finalize or look back to a design decision made.

![image](https://user-images.githubusercontent.com/8904368/104095171-a3676880-5295-11eb-946b-c5f0624a76de.png)
![image](https://user-images.githubusercontent.com/8904368/104095213-e32e5000-5295-11eb-8525-a11730951c1b.png)

![image](https://user-images.githubusercontent.com/8904368/104095200-c7c34500-5295-11eb-9105-505a959edb62.png)

**Comment by husaynali** [comment]
@IraklisDimitriadis any thoughts?

**Comment by IraklisDimitriadis** [comment]
I guess this happend during the rework. I would suggest to replace one of the two components (or the style used in that component) so that we have one theme in use.

**Comment by JohannesLipp** [comment]
Thank you. @husaynali do you prefer any of the two options?

**Comment by husaynali** [comment]
I am not a designer but seeing the trends community prefers Material design over the Ant Design. But this shall not overlook the rework required as the dashboard is completely done with Ant design. While in the graph editor Material design along with some bootstrap makes the sidebar and footer.

**Comment by husaynali** [comment]
@JohannesLipp  @IraklisDimitriadis   thoughts?

**Comment by JohannesLipp** [comment]
@husaynali you can choose :)
