### ISSUE TITLE
URLEncoding in URL when creating a new vocabulary

### ISSUE THREAD

**Issue by miselico** [Semantic-Society/Neologism#147]
When using a vocabulary with a special character (like space) in the name, it auto generates an URL wich just appends that string to the URL without encoding it.

Example with a space:
![Screenshot from 2021-04-19 10-04-15](https://user-images.githubusercontent.com/3889771/115202678-ed62b480-a0f6-11eb-91f9-8180c6c52944.png)

**Comment by JohannesLipp** [comment]
I totally agree, thanks for pointing this out! @husaynali please add this improvement, e.g., via `encodeURIComponent` in the `HttpParameterCodec` package. Thanks!

**Comment by husaynali** [comment]
implement this throughout.
