### ISSUE TITLE
Placement of the editing canvas controls

### ISSUE THREAD

**Issue by miselico** [Semantic-Society/Neologism#148]
Currently, the buttons to control the canvas are placed in the editing box and disappear on certain editing actions.

I suggest moving them on top of the canvas itself.

![Screenshot from 2021-04-19 11-56-57](https://user-images.githubusercontent.com/3889771/115217976-5c93d500-a106-11eb-8d94-0ca39d15e003.png)

**Comment by JohannesLipp** [comment]
Thanks for the hint! This might require major changes as the graph editor / canvas is a dedicated component based on mxGraph. I will discuss possible solutions with @husaynali on Thursday.

**Comment by husaynali** [comment]
Implement drawing elements/buttons on the canvas.
