### ISSUE TITLE
functionality of the reset button for canvas control

### ISSUE THREAD

**Issue by miselico** [Semantic-Society/Neologism#149]
There is a reset button to control the editing canvas.
Currently it only reset the zoom level. It would be reasonable to have it also center the vocabulary and perhaps also zoom such that the whole vocabulary becomes visible.

**Comment by JohannesLipp** [comment]
IMHO going to the dashboard and re-opening the graph editor solves this problem of "getting lost by panning too far". @husaynali can you please estimate the effort required to add this "panning back to center" to this button as well? Thanks!
