### ISSUE TITLE
Location of the domain text box in the editing component

### ISSUE THREAD

**Issue by miselico** [Semantic-Society/Neologism#150]
In the editing component, there is an editable box called 'domain'.
![Screenshot from 2021-04-19 12-01-25](https://user-images.githubusercontent.com/3889771/115218665-15f2aa80-a107-11eb-8fd3-64af4d63c792.png)

This should be part of the properties of the ontology, such as Name, URI, description and authors.

**Comment by JohannesLipp** [comment]
Thanks for the hint! @enisze added this as part of the batch recommendation system. It should be next to the "Get BatchBecommendation" button and should be renamed, as the term "domain" is indeed confusing. It actually means "Category" or "Tag" based on tags in LOV (cf. the tags below the cloud at https://lov.linkeddata.es/dataset/lov/ or https://lov.linkeddata.es/dataset/lov/vocabs?tag=Biology), and is used to improve the recommender functionality.

@enisze Could you please handle this? As is, put that text box next to the recommender button and rename it to something like "Domain of the vocabulary", "Vocabulary tag" or so? Plus, we might rethink if the placement it this sidebar makes sense.

**Comment by JohannesLipp** [comment]
Suggestion: At least add the "recommendation" elements in a dedicated component/box.
