### ISSUE TITLE
Remove Misleading error for current Rest middleware (simple:json.routes) due to missing typescript declarations in the log

### ISSUE THREAD

**Issue by alihussainiam** [Semantic-Society/Neologism#152]
Possible solutions:
- replace with some recent rest middleware
- look into type declarations and update accordingly with the new TS version

**Comment by husaynali** [comment]
![image](https://user-images.githubusercontent.com/8904368/116479007-45c84d80-a87f-11eb-9b55-aba37ae0847d.png)

Warning in the above image is shown for not finding the declaration of the module "meteor/simple:json-routes". Although the module is loaded and the routes do get declared and are usable which is the expected outcome of the module.

**Comment by husaynali** [comment]
Earlier it was suspected a type declaration is missing for the module. But the way Meteor atmosphere [package usage](https://guide.meteor.com/using-atmosphere-packages.html#using-atmosphere)   and double-checking the package.js code in the github code. which is 
`  api.export([
    'JsonRoutes',
    'RestMiddleware',
  ], 'server');
});`

The declaration is there but no clue why the runtime is not able to pick up the declaration but do load the module.

**Comment by husaynali** [comment]
There is a [post](https://www.codegrepper.com/code-examples/javascript/Could+not+find+a+declaration+file+for+module+%27react-dom%27.) that defines some vars to put end to this poking by the runtime by declaring var for the module. But shall we do it?

**Comment by husaynali** [comment]
as discussed per today's session, meteor upgrade does not work to fix this

**Comment by JohannesLipp** [comment]
#158 fixes parts of this, while upgrading from plain json-routes to restivus will remain open and might solve this issue here.

**Comment by JohannesLipp** [comment]
Invalid by now.
