### ISSUE TITLE
Change rdfs:description to rdfs:comment in the export

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#155]
`rdfs:description` does not exist. Please serialize these parts of the export to `rdfs:comment`.

**Comment by husaynali** [comment]
You mean to say "https://www.w3.org/2000/01/rdf-schema#description" is not found, so change to comment "https://www.w3.org/2000/01/rdf-schema#comment" ?

**Comment by JohannesLipp** [comment]
Exactly! Thanks for the quick fix!
