### ISSUE TITLE
Add support for DataTypeProperties

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#157]
We need support for datatype properties, which allow the user to add simple datatypes to classes. 

ObjectProperty (already in place) = Links one class (node) to another.
DatatypeProperty (not existing yet) = Adds a list of simple datatypes to a class. 

1. Please add support for the [XSD built-in datatypes](https://www.w3.org/TR/xmlschema-2/#built-in-datatypes), from which the user could choose from a dropdown field with autosuggest as depicted in this screenshot:
![image](https://user-images.githubusercontent.com/15930331/116888702-107b8100-ac2c-11eb-890d-176c09d5e907.png)
 
 Please include the all built-in types from "anyType" down to "unsignedBte/IDREFS", but only skip the white "all complex types" for now. 

2. Please update the export serialization by the following.
- Add these new things to the export via `owl:DatatypeProperty` instead of `owl:ObjectProperty` 
- Set the `rdfs:range` to the datatype the user chose, i.e., `https://www.w3.org/TR/xmlschema-2/#decimal` etc.

- [x] fixes enise branch styling break up on graph view

**Comment by JohannesLipp** [comment]
- Change "Add Properties" label in sidebar to "Add Property"
- Hide the current input fields for property creation, and show them on button click (2 buttons: "Object Property" and "Simple Data Property"
- Visualize DatatypeProperties in the graph (e.g., [as WebVowl does](http://www.visualdataweb.de/webvowl/))
- We enable editing via onClickListeners on these edges (different behavior: dropdown menu for "target" chooses from pre-defined datatypes instead of existing classes in the vocabulary)

**Comment by JohannesLipp** [comment]
- Please also update the export to include `owl:DatatypeProperty` for these
- Please update the `Property` schema definition in the readme

**Comment by husaynali** [comment]
New issue have arisen which needs to be addressed separately that is:

- listener for normal node clicks allows adding props to datatype itself

**Comment by husaynali** [comment]
- [ ] fixes enise branch styling break up on graph view
