### ISSUE TITLE
Verify packages

### ISSUE THREAD

**Issue by enisze** [Semantic-Society/Neologism#160]
Verify if packages are needed ( https://github.com/Semantic-Society/Neologism/blob/2bf8e0da6ce0c0744fb8df62cc4c8fe7750841f3/app/package.json#L50 )

    "ngx-contextmenu": "^5.4.0",
    "node-gyp": "^7.1.2",
    "python": "0.0.4",
    "zone": "^0.3.4",
    "ej-angular2": "^18.4.39"

**Comment by JohannesLipp** [comment]
It is required and we will not remove it.
