### ISSUE TITLE
Check styling

### ISSUE THREAD

**Issue by enisze** [Semantic-Society/Neologism#163]
Check if the deleted styling 

`style="height: 100vh;`

is needed in nz-sider

https://github.com/Semantic-Society/Neologism/blob/5c228a75a3969ee61ec3d2033d017c487cf43a16/app/src/app/mxgraph/mxgraph.component.html#L2

see commit:
https://github.com/Semantic-Society/Neologism/commit/543bbda86079770b88eae9974f35052bbc0c62d6

**Comment by JohannesLipp** [comment]
Solved
