### ISSUE TITLE
Move build pipeline 

### ISSUE THREAD

**Issue by enisze** [Semantic-Society/Neologism#166]
Move build pipeline from RWTH gitlab to public github

**Comment by alihussainiam** [comment]
@JohannesLipp  please share steps that have been tried and current issues so I can proceed.

**Comment by JohannesLipp** [comment]
> @JohannesLipp please share steps that have been tried and current issues so I can proceed.

I was able to fix it, see https://github.com/Semantic-Society/Neologism/pull/194 and https://github.com/Semantic-Society/Neologism/actions/runs/982687304
