### ISSUE TITLE
Ensure that the run/deploy instructions include all needed information

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#173]
E.g., the recently added `env.local.json` is not yet in the readme and thus might hinder users from running or deploying Neologism.

ISSUES:

1. server through Nginx unresolvable for client
2. dated readme for deploy and localhost instructs
3. user login is not possible becoz signup is disabled and guest user seeding instructs missing

**Comment by JohannesLipp** [comment]
Please also update the docker-compose file to use the publicly accessible GitHub.com container images instead of the private git.rwth-aachen ones. Please update the readme accordingly, thank you!

**Comment by alihussainiam** [comment]
@JohannesLipp  ok, but the remaining problem is not documentation but our requirement about not allowing users to sign and not creating a seed for guest users. With this, the user would be able to run but can not log in. How do you suggest handling this?

**Comment by JohannesLipp** [comment]
@alihussainiam good point! As you said, the options are

1. Explain in the readme how to manually create a guest account via the MongoDB `insertOne` command. Instructions would be a) start Neologism, b) stop Neologism, c) add guest user manually, d) start Neologism - correct?
2. Automate this entry either via Docker or in our Meteor components. This would be some effort on our side, but could also simplify the process for providers.

I would suggest option 1, because Neologism would stay guest-user-agnostic. Do you agree?

**Comment by alihussainiam** [comment]
> Explain in the readme how to manually create a guest account via the MongoDB insertOne command. Instructions would be a) start Neologism, b) stop Neologism, c) add guest user manually, d) start Neologism - correct?

Not just this, but you have to configure the image which can only be done at build time as of now, for the app to follow validate credentials. This can be avoided if we hardcode guest credentials and later on adapt the build process?

**Comment by alihussainiam** [comment]
After adopting changes in compose file and docker scripts I was able to connect all three (mongo,frontend,API) behind proxy on port 80. But there is a new problem/critical blocker specifically for meteor in for prod built.

After narrowing down the issue and trying diff options but nothing went successful.This remains a Critical blocker for this issue. I have now asked this where others had the same problem [link to the issue](https://github.com/meteor/meteor/issues/10733#issuecomment-894602516)

**Comment by JohannesLipp** [comment]
> After adopting changes in compose file and docker scripts I was able to connect all three (mongo,frontend,API) behind proxy on port 80. But there is a new problem/critical blocker specifically for meteor in for prod built.
> 
> After narrowing down the issue and trying diff options but nothing went successful.This remains a Critical blocker for this issue. I have now asked this where others had the same problem [link to the issue](https://github.com/meteor/meteor/issues/10733#issuecomment-894602516)

Thank you! I suggest to also re-open that other ticket so that it gets more awareness.

**Comment by JohannesLipp** [comment]
The investigations from the last week reported today yielded the following alternative plan: We replace the build-time URI for the runtime with a search & replace script that is being executed at container startup.
