### ISSUE TITLE
Create issues for open TODO items

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#177]
- List all todos
- Remove todos or create issues for these (and possibly merge multiple ones)
- In the source code (todo): Refer to the issue number (e.g., `// TODO (#123): <Todo text>`)

**Comment by alihussainiam** [comment]
Exported All TODOs
> └─ neologism2
   ├─ api
   │  └─ methods.ts (Implement User Auth for CRUD)
   │     ├─ line 110: TODO : Sanitize 
   │     ├─ line 116: TODO : Sanitize
   │     ├─ line 169: TODO : Sanitize
   │     └─ line 197: TODO : Sanitize
   └─ src
      ├─ batchRecommender
      │  └─ batchRecommender.component.html
      │     └─ line 3: TODO : add anchor for references (see standardView.component.html)
      ├─ editbox
      │  ├─ editbox.component.ts
      │  │  ├─ line 31: TODO : as this is an observable, does it need @Input?
      │  │  ├─ line 39: TODO : strictly speaking, this component does not need this as it only needs access to classes and properties.
      │  │  └─ line 134: TODO is there a better way in JS?
      │  └─ editbox.service.ts
      │     └─ line 86: TODO : is this a good way to do this?
      ├─ mxgraph
      │  ├─ standardView
      │  │  └─ standardView.component.html
      │  │     └─ line 2: TODO : add anchor for references
      │  ├─ N3Codec.ts
      │  │  ├─ line 85: TODO Michael: Assuming string[] returned
      │  │  ├─ line 146: TODO Michael: Assuming string[] returned
      │  │  └─ line 165: TODO : Not exactly foolproof
      │  ├─ dynamicGrid.ts
      │  │  └─ line 29: TODO attach window resize listener
      │  ├─ mxgraph.component.ts
      │  │  ├─ line 115: TODO : Currently creates a new instance with each subscription. Use something like this instead: .multicast(new BehaviorSubject([]));
      │  │  ├─ line 177: TODO It looks like this currently leaks observables.
      │  │  └─ line 289: TODO : is this better solved with a ES6 Map?
      │  └─ mxgraph.ts
      │     ├─ line 46: TODO : Implement this in the future?
      │     ├─ line 140: TODO Michael does this need to be implemented?
      │     ├─ line 146: TODO Michael does this need to be implemented?
      │     ├─ line 174: TODO : Check if multiple listener on same event creating UI flow disturbances
      │     ├─ line 230: TODO in principle getCell should work, but upon inserting there is an issue and the cell gets assigned a new id
      │     ├─ line 302: TODO : Assert this clear selection model
      │     └─ line 307: TODO : Assert this clear selection model
      ├─ recommender
      │  └─ recommender.component.ts
      │     ├─ line 39: TODO REFACTOR THIS
      │     ├─ line 41: TODO MC: I don't know a better way to ensure that an old finishing request does not turn of the spinner OR fills the results.
      │     ├─ line 42: TODO before it was be possible that an old, still pending request which returns turns off the spinner or fills the result list
      │     ├─ line 89: TODO re-enable context
      │     └─ line 96: TODO handle error?
      ├─ services
      │  └─ vocabularies.service.ts
      │     ├─ line 79: TODO : Breaks upon deletion
      │     └─ line 293: TODO : this following steps are overkill. We can use something more granular later.
      ├─ vocablist
      │  └─ vocablist.component.ts
      │     └─ line 44: TODO : Move to VocabService #decouple
      └─ vocabulary-editor
         ├─ mx-graph-editor
         │  └─ mx-graph-editor.component.ts
         │     ├─ line 48: TODO : Currently creates a new instance with each subscription. Use something like this instead: .multicast(new BehaviorSubject([]));
         │     ├─ line 75: TODO It looks like this currently leaks observables.
         │     └─ line 151: TODO : is this better solved with a ES6 Map?
         ├─ edit.component.service.ts
         │  └─ line 85: TODO : is this a good way to do this?
         └─ vocabulary-editor.component.ts
            ├─ line 75: TODO : as this is an observable, does it need @Input?
            ├─ line 83: TODO : strictly speaking, this component does not need this as it only needs access to classes and properties.
            ├─ line 205: TODO is there a better way in JS?
            └─ line 255: TODO : Call the updateClass (needs to be implemented) of vocabService and call toggleEdit() afterwards

**Comment by alihussainiam** [comment]
└─ neologism2
   ├─ methods.ts
   │  ├─ line 110: TODO (#183): Sanitize
   │  ├─ line 116: TODO (#183): Sanitize
   │  ├─ line 169: TODO (#183): Sanitize
   │  └─ line 197: TODO (#183): Sanitize
   ├─ batchRecommender.component.html
   │  └─ line 10: TODO (185): add anchor for references (see standardView.component.html)
   ├─ editbox.component.ts
   │  ├─ line 31: TODO (184): as this is an observable, does it need @Input?
   │  ├─ line 39: TODO (184): strictly speaking, this component does not need this as it only needs access to classes and properties.
   │  └─ line 134: TODO (184): is there a better way in JS?
   ├─ editbox.service.ts
   │  └─ line 86: TODO (184): is this a good way to do this?
   ├─ N3Codec.ts
   │  ├─ line 85: TODO Michael (186): Assuming string[] returned
   │  ├─ line 146: TODO Michael (187): Assuming string[] returned
   │  └─ line 165: TODO (187): Not exactly foolproof
   ├─ dynamicGrid.ts
   │  └─ line 29: TODO (187) attach window resize listener
   ├─ mxgraph.component.ts
   │  ├─ line 116: TODO (18): Currently creates a new instance with each subscription. Use something like this instead: .multicast(new BehaviorSubject([]));
   │  ├─ line 178: TODO (186): It looks like this currently leaks observables.
   │  └─ line 290: TODO (184): is this better solved with a ES6 Map?
   ├─ mxgraph.ts
   │  ├─ line 46: TODO (187): Implement this in the future?
   │  ├─ line 140: TODO (187):Michael does this need to be implemented?
   │  ├─ line 146: TODO (187): Michael does this need to be implemented?
   │  ├─ line 174: TODO (186): Check if multiple listener on same event creating UI flow disturbances
   │  ├─ line 230: TODO (186): in principle getCell should work, but upon inserting there is an issue and the cell gets assigned a new id
   │  ├─ line 302: TODO (183): Assert this clear selection model
   │  └─ line 307: TODO (183): Assert this clear selection model
   ├─ standardView.component.html
   │  └─ line 2: TODO (185): add anchor for references
   ├─ recommender.component.ts
   │  ├─ line 39: TODO (189) REFACTOR THIS
   │  ├─ line 41: TODO (189) MC: I don't know a better way to ensure that an old finishing request does not turn of the spinner OR fills the results.
   │  ├─ line 42: TODO (189) before it was be possible that an old, still pending request which returns turns off the spinner or fills the result list
   │  ├─ line 89: TODO (187) re-enable context
   │  └─ line 96: TODO (187) handle error?
   ├─ vocabularies.service.ts
   │  ├─ line 79: TODO (186): Breaks upon deletion
   │  └─ line 293: TODO (184): this following steps are overkill. We can use something more granular later.
   ├─ vocablist.component.ts
   │  └─ line 44: TODO (188): Move to VocabService #decouple
   ├─ edit.component.service.ts
   │  └─ line 85: TODO (184): is this a good way to do this?
   ├─ mx-graph-editor.component.ts
   │  ├─ line 48: TODO 18: Currently creates a new instance with each subscription. Use something like this instead: .multicast(new BehaviorSubject([]));
   │  ├─ line 75: TODO (186) It looks like this currently leaks observables.
   │  └─ line 151: TODO (184): is this better solved with a ES6 Map?
   └─ vocabulary-editor.component.ts
      ├─ line 75: TODO (186): as this is an observable, does it need @Input?
      ├─ line 83: TODO (184): strictly speaking, this component does not need this as it only needs access to classes and properties.
      ├─ line 205: TODO (184)is there a better way in JS?
      └─ line 255: TODO (187): Call the updateClass (needs to be implemented) of vocabService and call toggleEdit() afterwards

**Comment by alihussainiam** [comment]
added issues and updated todos
