### ISSUE TITLE
Get multicast to work

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#18]
There are many places in the code where a multicast seems to make sense.
However, this does not seem to work anywhere. Figure out why not and start using multicast.

**Comment by JohannesLipp** [comment]
@miselico initially raised this issue. As soon as we tackle this, it might be required to ask him for details.

**Comment by miselico** [comment]
Off the top of my head, the point here was that there were several places in the UI where the same information is used. Currently they each use their own subscription to receive push updates from meteor (trough the collections), while doing one of these subscription combined with a multicast would reduce the number of subscriptions needed.

**Comment by alihussainiam** [comment]
- Multicast usage commented in code over the methods is uncertain, as they are not sharing the same results on exec
- Meteor Publications are emitting composite data forms, and also subscriptions are done once and gracefully closed.
- From the past an inactive state service component using Subject (multicast derivative) in place of getter setter but the purpose is undefined

**Comment by JohannesLipp** [comment]
As proposed by @alihussainiam , adding multicast is not beneficial / promising at the current state of our project.
