### ISSUE TITLE
"Edit vocabulary" button is not working

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#180]
![image](https://user-images.githubusercontent.com/15930331/120325689-30b06580-c2e8-11eb-8b90-d4fa8152e0ee.png)

Clicking this button on the dashboard does not do anything. Please reproduce and fix - thank you!

**Comment by alihussainiam** [comment]
@JohannesLipp Quickly checked and found the handler is not implemenetd

**Comment by JohannesLipp** [comment]
Decision: Remove this button, as its only useful feature is updating a vocabulary's description.
