### ISSUE TITLE
updates of classes by others causes propertylist to collapse

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#20]
When another user A edits a class alpha's name and user B is looking at the properties of class beta, which has a property with range alpha. Then, the list of class beta will close when A updates.

Task: Reproduce, then fix.

**Comment by husaynali** [comment]
The issue is invalid because now we don't have any view where one collectively see the properties of a class but on the graph view itself where this becomes invalid as well.

**Comment by husaynali** [comment]
@JohannesLipp This is subject to mark as Invalid and Close.

**Comment by JohannesLipp** [comment]
Not applicable anymore.
