### ISSUE TITLE
adapting neologism docker build for missing env

### ISSUE THREAD

**Issue by alihussainiam** [Semantic-Society/Neologism#209]
configure nginx to serve published vocabs using storageLocation env

**Comment by alihussainiam** [comment]
@JohannesLipp  I find a new issue with the published vocab feature but unable to reproduce that from last you deployed and went to white screen. steps to reproduce ?

**Comment by JohannesLipp** [comment]
> 

@alihussainiam could you please rephrase that? I do not get your point.. Sorry!

**Comment by alihussainiam** [comment]
your comment "A complete refresh now rendered a blank page only, too"
![Clipboard - 18  Januar 2022 11_41](https://user-images.githubusercontent.com/8904368/150781990-bf197387-0155-44c7-ac8b-74cbb8b62efa.png)
