### ISSUE TITLE
Only Display "Edit Properties" if Class has Properties

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#219]
![image](https://user-images.githubusercontent.com/15930331/161967436-8fb54e78-79c5-42a1-bbed-d51d708cb311.png)

If a class has no properties assigned, the "edit props" button does not make sense: 
![image](https://user-images.githubusercontent.com/15930331/161967520-de90c1cc-13ca-4e87-ae04-5083e4ac7710.png)

Please only display it if the selected class actually has properties. Thanks!

**Comment by alihussainiam** [comment]
@JohannesLipp [please review](https://github.com/Semantic-Society/Neologism/tree/758d32b90a30ac0525e7c4d663cfbabd64e34b9c)

**Comment by JohannesLipp** [comment]
Looks good, esp. https://github.com/Semantic-Society/Neologism/commit/758d32b90a30ac0525e7c4d663cfbabd64e34b9c  thank you!

How will this be integrated into the main branch? Is it already in ma-hussain and will implicitly merge to main from there later?

**Comment by alihussainiam** [comment]
Thanks Johannes. Yes it will be merged later into main
