### ISSUE TITLE
Options popup is not working + is displayed weirdly

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#220]
![image](https://user-images.githubusercontent.com/15930331/161967825-f7be1f9e-1759-455f-9dbd-de58368dd60c.png)

Do we even have options? If not, please remove that button. If yes, please place the popup properly. Thank you!

**Comment by alihussainiam** [comment]
@JohannesLipp [please review](https://github.com/Semantic-Society/Neologism/tree/288df814dff4352f85d2d0ea3bd234fa49a15434)

**Comment by JohannesLipp** [comment]
Solved on the `thesis-hussain` branch, will be merged to `main` soon.
