### ISSUE TITLE
Sanity checking of duplicate URIs

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#31]
Many sanity checks can be done, but this is perhaps the most important one. If there are duplicate URIs in the model, things can get rather weird.

**Comment by JohannesLipp** [comment]
A possible solution to this issue would be to prevent term creation, if the given URI is already present in the ontology.

**Comment by husaynali** [comment]
@JohannesLipp As per comments above the scope of term creation that is adding a new class/property but NOT edit is going to be the target. Other places such as edit for prop/class requires work for extending the same validation because of multiple styling components used as of now.
