### ISSUE TITLE
Implement Functionality of the Edit button on the vocabulary overview page

### ISSUE THREAD

**Issue by lgleim** [Semantic-Society/Neologism#39]
![image](https://user-images.githubusercontent.com/3898904/90769882-402e6700-e2f1-11ea-8df6-9b04015b0abd.png)

At the same time, vocab Name should probably be made clickable (i.e. a link) and the vocab ID hidden

**Comment by ousseinali** [comment]
updating list of contributors is part of meta or it shall be managed separately? currently, you can add users but not update in any way.

**Comment by JohannesLipp** [comment]
I would assume that the "edit vocab" button should enable the user to edit

- The vocab name
- The vocab namespace/URI
- The vocab Description
- The Contributors

The open question is, whether "neologism contributor" (=someone has access to a vocab, and can modify it) in that context is intended to be the same as "ontology contributor" (=an `dct:contributor` or `dct:creator` in the output RDF file) 
@lgleim @miselico What is you opinion on this?

**Comment by JohannesLipp** [comment]
@lgleim @miselico Could you please response to above question? Thank you!

**Comment by JohannesLipp** [comment]
Decision: Remove the "edit vocab button" and clicking on a vocab's name should redirect to the graph editor.
