### ISSUE TITLE
Merge "Add new Class/Property" and "Recommend X" functionality

### ISSUE THREAD

**Issue by lgleim** [Semantic-Society/Neologism#40]
![image](https://user-images.githubusercontent.com/3898904/90770245-c5b21700-e2f1-11ea-8029-7bca6bef816a.png)

Merge these into only one component that suggests existing classes / properties before allowing you to create new ones

**Comment by JohannesLipp** [comment]
Outdated, as we removed the recommendations for now. We will take this into account when we integrate recommenders again.
