### ISSUE TITLE
Fix security alerts coming from old dependencies

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#48]
Cf. to https://github.com/Semantic-Society/Neologism/network/alerts

In …/docker/package-lock.json, please 

- Upgrade bl to version 2.2.1 or later. 
- Upgrade bcrypt to version 5.0.0 or later.

Please inspect the two automatically generated solutions in the merge requests, before starting any implementation. Thanks.

**Comment by ousseinali** [comment]
> Cf. to https://github.com/Semantic-Society/Neologism/network/alerts
> 
> In …/docker/package-lock.json, please
> 
> * Upgrade bl to version 2.2.1 or later.
> * Upgrade bcrypt to version 5.0.0 or later.
> 
> Please inspect the two automatically generated solutions in the merge requests, before starting any implementation. Thanks.

can you please check if the link to alert is still working?

**Comment by JohannesLipp** [comment]
> > Cf. to https://github.com/Semantic-Society/Neologism/network/alerts
> > In …/docker/package-lock.json, please
> > 
> > * Upgrade bl to version 2.2.1 or later.
> > * Upgrade bcrypt to version 5.0.0 or later.
> > 
> > Please inspect the two automatically generated solutions in the merge requests, before starting any implementation. Thanks.
> 
> @JohannesLipp can you please check if the link to alert is still working?

Yes, it works for me. These alerts might only be available to the group owner (me). Can you inspect this via the auto-generated pull requests instead? #49 and #50
