### ISSUE TITLE
Reduce CPU load for front page

### ISSUE THREAD

**Issue by miselico** [Semantic-Society/Neologism#60]
The front page has a nice interactive animation. However, sometimes this is very CPU intensive.
A less intensive solution should be found. Perhaps a static image?

**Comment by JohannesLipp** [comment]
I could not reproduce this so far. As long as the browser tab is not selected/shown but in the background, the animation is on hold and does not produce CPU load. I will do a longer test now, and leave that tab open while the animation is active. Will report back then.

**Comment by JohannesLipp** [comment]
Okay, I agree with you. Just having the animation open causes about 10% CPU load on my i7-8650U.

Clicking on the animation creates additional elements in the animation and quickly raises the load to ~20%.

**Comment by JohannesLipp** [comment]
My suggestions: Either 
1) replace with a static image or 
2) reduce the CPU load somehow, as the user usually does not spend too long on the login page.
