### ISSUE TITLE
Sketch out Workflows

### ISSUE THREAD

**Issue by husaynali** [Semantic-Society/Neologism#66]
@JohannesLipp please write the workflow titles to find for and the objective associated with the task.

**Comment by JohannesLipp** [comment]
- Create a simple vocab (including rdf export)
- edit an existing vocab
- edit a vocab collaboratively
- view and understand an existing vocab

**Comment by husaynali** [comment]
tools:
flow diagram

**Comment by husaynali** [comment]
[Flowchar Image to Create Vocabular](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=create_vocab#R7Vtbb9s2GP01BtIHG7rLeozjtMXQDV2DbunTQEu0zJUSNYqO7f36kRJlS6R8aWNLc5KiaCXeeb7D70Z5YN8l6w8UZItfSQTxwDKi9cCeDiwrMHz%2BryjYlAW%2BbZUFMUVRWWTuCh7Qv1AWGrJ0iSKYNxoyQjBDWbMwJGkKQ9YoA5SSVbPZnODmrBmIoVbwEAKsl%2F6JIraQpaYX7Co%2BQhQv5NRjS254BsLvMSXLVM43sOx58aesTkA1ltxovgARWdWK7PuBfUcJYeVTsr6DWEBbwVb2e7%2BndrtuClN2SgcplieAl3LrOQOUycWxTQUIX2cmHpN1LAQ%2BmmOyChe85YhBmqAUMEIH9iRnlHzfQsZ3M%2BHNI8QXc0ewaDFNSQprxVNEufwQSYsqKrpN5iRlD3Jqg78vWIL5o8kf9e3JHT9ByuC6ViS3%2BwGSBDK64U1kreVJ6CU1q9dVTc6VdBY1EduyDEhqxduRd%2FDyB4lwO9q%2Bhmt9r%2BYWwAoszh7DsG3P06A1T8QlJ0sawoasYdTgvg4UhRgw9NQ8Cm3bll0%2FE8Rn3QJsW02ATRU5TrAYMtlLAW%2B7jJPwHHeO58XBM4ORYzbxCxT8Splq%2BJ0ylsbi88nCMTRVArkWfD2KxK%2BMQxea5JfH3yeTzddNgjfBX48sdOOPX4fuWBPBwPIwE3hmIG0IwvtnKWzMJCzhvBXUjWc3fGn8L5%2FeqD29E48CM0MgOpyDBOFN2YcPBJKsqLRtR2AM8RNkKARaTXOQvLD5YgjTytZKXblKUclFmQDcrF5JLEW9U66zqMSQcQ4N%2BVZDlMat%2Fblo2RBgFKdldcjFD2mzGqVRQQpRb9SWVlQyCtJ8zgethuckrBqsCI2as9e77zyDoYK55Yy3WFtOsHt2a8hHKM8wkKijFKPaxPwMAVZfUCVc%2FhQXQsYo%2FC7WsGSMCB7cfMbL%2FF1FjhmtGm6Fls5y8R8jvDHJYKpWVF05T0tqbfu%2F0e3V0y1CAJO4wI8eIYqg3htNro8mqsjfDv61S%2FQcBz%2BFK173REIwW2IgPJo6K9pNzBEF8aY3XhTL3vTGS5PoOfRGseB9B14JIIslwkiGdKsFYvCB70nUrnhEOWgJ87SYriXy2x%2FmuW57OqMe5lVl9TBvfKkwzzNbwjwFJZGnqEJfEQ2TmKQA3%2B9KJ00cd20%2BEZJJ9P7mhN3I5CxY8ligBVslIXI0CdUeuMrIucxGHNq60S6rk7Muz4uvg73xtTj4gukgbKqvurpRSP8eFTOyBSwUhzgBpcNszBHEUV4cmJYATSkxR4rJNVKQiCFvhEJ4VxxVtY81ks3y4uTItuWpjuAcLDErdafSzxb9MgrniOuNyXaA9kkaazqwGEcMCsIQ5rlomC1nPFrl8skoegIMtkeplaoocf%2BfqgrrVFVhehfTFfZL0xUVVMd1hdWnrvD81wu8d47U%2BC2lYFNrkIkcdb4%2Fc%2B5Ud4fy8DmuczA7fqQ9fyhX8LP58FZofD1J%2Fhtp5cUnMIO4KUvpF06lU8g1LFdW3LTgW1mRoCgqaQO5%2Bwpm28S3xI4P7k4G7vSQtpM3qrLzYHtRWWfMAcLv1Y1DY2QZlTaSkA%2FlkXjmncnQNJp6d2h6zTHIfJ7D515wHDwUNYHeJxnb6LZoQZLZMu%2FGDo0VapuOZofGXXqsY%2FfFKUPrRGU4dnq1QpYG%2FB91tyykkLtY%2Bi1dBxxVbs9cp8VXars9u5yrpJP0G8w1aApP%2BWJ6WZC2TD2cC2j1Ot4JdGXgtOBsXQpnv5ezz9Gim8f6yzcx2MitXqdrOXj5tpFv59QZ3ok649me6085UK6hnEhf%2BXTox9pfyIFyeyWPMfJ8t04gc2TY9hEKFW%2BfIUV880I%2FXDmv9O9MnCYRPEdxv%2FZ8ZPLDBFXncQ8T1FY%2BflHaX4aglTBqVqRM9PToD2ontSUv0ak%2F6OtZidtU95mvzdQ6toKzq%2BPcranVkxC3LVy8Ppyb8Z7Xwue2NNvFcA68XqzSGrHHnRPD377VanbGSLw0bFGt09YR6s4NGtsnmqug1wTeWNdRU7JKMQE8XDJGNJoPRKYei%2FR58ZnUguTC%2BCQgXBSXX6rC7zgZ7SvG0ug7vhrrlrGPU3NOJjsnMrnkUm9MfnGp6DbgnV6vBqsV1fOA64yIX1IYX6bvdW3QYzrQa3FLOnX%2Fqg%2FaX1imxXIVnP2e3b%2FAvvJz%2FmwPYE9gqKTEfEeRwJkCVmvPPPsC1iPtLxOwBvqPkrrMqAyNkWGMmzk5z%2FR7TqkEVleWfc%2FlpKJJLveznYPbrynoLzCDQP9dYJd2LFBOR4tH260Z0z8HEpe5%2BtcqV27XTCWU8K2Lhdv8dffb15LNu98X2%2Ff%2FAQ%3D%3D)

**Comment by husaynali** [comment]
> *~~ Create a simple vocab (including rdf export) <-- The most important one for now~~
> * edit an existing vocab  ** (feature not available) **
> * edit a vocab collaboratively 
> * view and understand an existing vocab ** ?? **
> 
> This is to achieve the ultimate goal of an easy-to-use system with proper/clear instructions
